Remove parseArgs with newMain parameter (#212)
* fix(parseArgs): Avoid template constraint to provide a better error message

Currently, when a user's main does not compile, they get a barely readable
error message, which looks like:
```
argparse/source/argparse/api/cli.d(196,65): Error: none of the overloads of `parseArgs` are callable using argument types `(string[])`
argparse/1.4.1/argparse/source/argparse/api/cli.d(93,19):        Candidates are: `argparse.api.cli.CLI!(Config('=', '\xff', '-', "--", true, false, true, StylingMode.autodetect, null, Style(TextStyle([cast(ubyte)1u]), TextStyle([cast(ubyte)1u]), TextStyle([cast(ubyte)1u, cast(ubyte)4u]), TextStyle([cast(ubyte)93u]), TextStyle([cast(ubyte)3u]), TextStyle([cast(ubyte)93u])), null), Arguments).parseArgs(ref Arguments receiver, string[] args)`
argparse/1.4.1/argparse/source/argparse/api/cli.d(105,16):                        `parseArgs(alias newMain)(string[] args, auto ref COMMAND initialValue = COMMAND.init)`
  with `newMain = __lambda_L92_C27(__T1)(args)`
  must satisfy the following constraint:
`       __traits(compiles, ()
{
newMain(initialValue);
}
)`
argparse/1.4.1/argparse/source/argparse/api/cli.d(123,16):                        `parseArgs(alias newMain)(string[] args, auto ref COMMAND initialValue = COMMAND.init)`
  with `newMain = __lambda_L92_C27(__T1)(args)`
  must satisfy the following constraint:
`       __traits(compiles, ()
{
newMain(initialValue, string[].init);
}
)`
source/main.d(92,1):        parent scope from here: `mixin main!((args)
{
return args.cmd.match!((CSACommand cmd)
{
return createServiceAccount(cmd);
}
, (SyncIDCommand cmd)
{
return synchronizeIdentities(cmd);
}
, (SyncHierarchyCommand cmd)
{
return 0;
}
, (DefaultCmd cmd)
{
Arguments dummy;
CLI!Arguments.parseArgs(dummy, ["-h"]);
return 1;
}
);
}
)`
```
This is because none of the `__traits(compiles)` on the template constraints matches.
By not using those constraints, and having a fallback to a simple call, we instead
get the following error message:
```
std/sumtype.d(1983,13): Error: static assert:  "`handlers[2]` of type `int function(SyncHierarchyCommand cmd) pure nothrow @nogc @safe` never matches. Perhaps the handler failed to compile"
std/sumtype.d(1647,52):        instantiated from here: `matchImpl!(SumType!(CSACommand, SyncIDCommand, Default!(DefaultCmd)))`
source/main.d(94,20):        instantiated from here: `match!(SumType!(CSACommand, SyncIDCommand, Default!(DefaultCmd)))`
argparse/1.4.1/argparse/source/argparse/api/cli.d(122,20):        instantiated from here: `__lambda_L92_C27!(Arguments)`
argparse/1.4.1/argparse/source/argparse/api/cli.d(182,65):        instantiated from here: `parseArgs!(__lambda_L92_C27)`
```

In this instance, the error becomes much easier to spot
(said user added a subcommand, but forgot to add it to the sumtype).

* Add main1

* Unit tests cleanup

* Invert if condition

* Remove CLI.parseArgs with newMain

* Rewrite CLI.main template

* Delete call_parser3 snippet

* Fix unit tests

* Fix documentation

* Update readme

---------

Co-authored-by: Andrey Zherikov <andrey.zherikov@gmail.com>